version: "3.8"
services:
  redis:
    env_file:
      - .env.redis
      - "${SERIAL_NUMBER}/.env.redis"
    image: "${REGISTRY_USER}/redis:${REDIS_TAG}"
    expose:
      - "6379"
  audio_collector_1:
    env_file:
      - .env.audio_collector
      - "${SERIAL_NUMBER}/.env.audio_collector"
    environment:
      - CHANNEL=1
    image: "${REGISTRY_USER}/audio_collector:${AUDIO_COLLECTOR_TAG}"
    privileged: true
    depends_on:
      - redis
  audio_collector_2:
    env_file:
      - .env.audio_collector
      - "${SERIAL_NUMBER}/.env.audio_collector"
    environment:
      - CHANNEL=2
    image: "${REGISTRY_USER}/audio_collector:${AUDIO_COLLECTOR_TAG}"
    privileged: true
    depends_on:
      - redis
  classifier:
    env_file:
      - .env.classifier
      - "${SERIAL_NUMBER}/.env.classifier"
    image: "${REGISTRY_USER}/classifier:${CLASSIFIER_TAG}"
    depends_on:
      - redis
  cloud_publisher:
    env_file:
      - .env.cloud_publisher
      - "${SERIAL_NUMBER}/.env.cloud_publisher"
    env_file: .env.cloud_publisher
    image: "${REGISTRY_USER}/cloud_publisher:${CLOUD_PUBLISHER_TAG}"
    depends_on:
      - redis
