version: "3.8"
services:
  redis:
    image: "${REGISTRY_USER}/redis:${REDIS_TAG}"
    expose:
      - "6379"
  audio_collector_1:
    env_file:
      - .audio_collector.env
      - "${SERIAL_NUMBER}/.audio_collector_1.env"
    image: "${REGISTRY_USER}/audio_collector:${AUDIO_COLLECTOR_TAG}"
    privileged: true
    depends_on:
      - redis
  audio_collector_2:
    env_file:
      - .audio_collector.env
      - "${SERIAL_NUMBER}/.audio_collector_2.env"
    image: "${REGISTRY_USER}/audio_collector:${AUDIO_COLLECTOR_TAG}"
    privileged: true
    depends_on:
      - redis
  classifier:
    env_file:
      - .classifier.env
    image: "${REGISTRY_USER}/classifier:${CLASSIFIER_TAG}"
    depends_on:
      - redis
  cloud_publisher:
    env_file:
      - .cloud_publisher.env
    environment:
      - SERIAL_NUMBER=${SERIAL_NUMBER}
    image: "${REGISTRY_USER}/cloud_publisher:${CLOUD_PUBLISHER_TAG}"
    depends_on:
      - redis
